name = "neptunepvptiers"
pages_build_output_dir = "dist"
compatibility_date = "2026-08-13"

[vars]
DISCORD_GUILD_ID = "YOUR_GUILD_ID"
DISCORD_CLIENT_ID = "YOUR_DISCORD_CLIENT_ID"

[[kv_namespaces]]
binding = "TIERLIST_KV"
id = "YOUR_KV_NAMESPACE_ID"
